/**
 * FaceAuth Contract Deployment Script
 * This script deploys the FaceAuth smart contract and outputs the contract address
 */

const Web3 = require('web3');
const fs = require('fs');
const path = require('path');

// Contract ABI (simplified for deployment)
const contractABI = [
    {
        "inputs": [
            {"internalType": "string", "name": "username", "type": "string"},
            {"internalType": "string", "name": "passwordHash", "type": "string"},
            {"internalType": "string", "name": "faceHash", "type": "string"}
        ],
        "name": "registerUser",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [{"internalType": "string", "name": "username", "type": "string"}],
        "name": "getUserHash",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [{"internalType": "string", "name": "username", "type": "string"}],
        "name": "isRegistered",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function"
    }
];

async function deployContract() {
    try {
        console.log('🚀 Starting FaceAuth contract deployment...');
        
        // Connect to Ganache
        const web3 = new Web3('http://127.0.0.1:7545');
        
        // Check connection
        const isConnected = await web3.eth.isSyncing();
        console.log('✅ Connected to Ganache');
        
        // Get accounts
        const accounts = await web3.eth.getAccounts();
        if (accounts.length === 0) {
            throw new Error('No accounts available. Make sure Ganache is running.');
        }
        
        console.log(`📋 Using account: ${accounts[0]}`);
        
        // Read contract bytecode (this would be generated by Truffle)
        // For demo purposes, we'll use a placeholder
        const contractBytecode = '0x608060405234801561001057600080fd5b50...'; // This would be the actual bytecode
        
        // Deploy contract
        const contract = new web3.eth.Contract(contractABI);
        const deploy = contract.deploy({
            data: contractBytecode,
            arguments: []
        });
        
        const deployedContract = await deploy.send({
            from: accounts[0],
            gas: 2000000
        });
        
        const contractAddress = deployedContract.options.address;
        console.log(`✅ Contract deployed at: ${contractAddress}`);
        
        // Save contract address to file
        const contractInfo = {
            address: contractAddress,
            abi: contractABI,
            network: 'ganache',
            deployedAt: new Date().toISOString()
        };
        
        fs.writeFileSync(
            path.join(__dirname, 'contract-info.json'),
            JSON.stringify(contractInfo, null, 2)
        );
        
        console.log('📄 Contract info saved to contract-info.json');
        console.log('🔧 Update your Django settings with the contract address');
        
        return contractAddress;
        
    } catch (error) {
        console.error('❌ Deployment failed:', error.message);
        process.exit(1);
    }
}

// Run deployment
deployContract();

